[package]
name = "anka-cli"
description = "Command-line interface for Anka"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "anka"
path = "src/main.rs"

[features]
stats = ["anka-index/stats"]

[dependencies]
anka-core.workspace = true
anka-index.workspace = true
anka-store.workspace = true

anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
